### PR TITLE
change module structure

### PR DESCRIPTION
**Pull request by jtatia**
Change In module Structure so that the module loads

### CODE REVIEW

**Comment by wluyima** [comment]
Did you try to fix why the module couldn't load? In theory it should be able to load if you do things the right way, we do have modules like this and they are able to load, so I don't understand why this couldn't.

**Comment by jtatia** [comment]
@wluyima Yes. I tried searching for a way to solve it bust wasn't able to. Also I didn't find any module like this. And by just changeing it to org.openmrs.module.tag it started working.

**Comment by wluyima** [comment]
event module is like this

**Comment by wluyima** [comment]
What was the error you were getting?

**Comment by jtatia** [comment]
the event module is org.openmrs.event while in core it is org.openmrs   . should i try it like it is done in event module.  the error was: https://pastebin.com/szHih2J8

**Comment by wluyima** [comment]
That's what am eluding to, it was supposed to be changed to `org.openmrs.tag` and not `org.openmrs.module.tag`

**Comment by jtatia** [comment]
ok, ill do that right away

**Comment by wluyima** [comment]
Not that you have to, I was just wondering, just leave it as org.openmrs.module.tag in the meantime since you already changed it

**Comment by jtatia** [comment]
if org.openmrs.tag is correct we should follow it. I already made the change and made a new pull request. :)

**Comment by wluyima** [comment]
If it work it's fine. It's good to first talk and agree before making such major changes rather than working on them right away, it saves you a lot of time.

**Comment by jtatia** [comment]
Really sorry about that. I was trying to get the module to load, and once i managed that i kept on coding. I'll keep this in mind next time :)

**Pull request closed without merging**
