### PR TITLE
Angular ui

### PR DESCRIPTION
**Pull request by jtatia**
added Angular app.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@jtatia do you plan to squash these commits?

**Comment by jtatia** [comment]
lets keep them like this for now. If everything is well and good by the end of the review and if there is a need, ill squash the commits. We might require the commit history :-)

**Comment by dkayiwa** [comment]
oh i see! 👍

**Comment by wluyima** [comment]
Some concerns with this PR,
- Why do you have to change the package namespace now? I see that initially you didn't include module in the namespace which could be fine since we intend to move this to core, do some things not work if you don't change it?
- If you really have to change the package namespace please do it in a different PR from that that with the UI changes, otherwise reviewing this with all these changes mixed up might be troublesome

**Comment by jtatia** [comment]
@wluyima  yes. the module does not get loaded without having the module namespace. i created a completely new module and tested it. turns out by changing it to org.openmrs the module wasn't getting loaded. 
What ill do is as you suggested, first create a new pr with only changes in the structure, and another with the angular part once it gets merged.

**Comment by wluyima** [comment]
Can you close this PR? Where is the PR with just the UI changes?

**Comment by jtatia** [comment]
I'll add that after #6 gets merged.

**Pull request closed without merging**
